baseurl = "http://showerphoto.by/"
googleAnalytics = "UA-XXXXXXX-Y"
languageCode = "en-us"
theme = "phugo"
title = "Showerphoto"
[params]
author = "aerohub"
description = "Phugo - Photo Gallery on Hugo"
keywords = "phugo, hugo, photogallery, photoblog, hugo theme"
[params.footer.contact]
buttontext = "Send"
headline = "Get in touch"
realemail = "example@examle.org"
resettext = "Reset"
[params.footer.contact.email]
text = "Email *"
warning = "Please, enter your email."
[params.footer.contact.message]
text = "Message *"
warning = "Please, enter your message"
[params.footer.contact.name]
text = "Name *"
warning = "Please, enter your name"
[params.footer.copyright]
name = "Your name"
[params.footer.paragraph]
headline = "Magna feugiat sed adipiscing"
text = "Nulla consequat, ex ut suscipit rutrum, mi dolor tincidunt erat, et scelerisque turpis ipsum eget quis orci mattis aliquet. Maecenas fringilla et ante at lorem et ipsum. Dolor nulla eu bibendum sapien. Donec non pharetra dui. Nulla consequat, ex ut suscipit rutrum, mi dolor tincidunt erat, et scelerisque turpis ipsum."
[params.footer.social]
headline = "Follow me"
[[params.footer.social.links]]
icon = "fa-twitter"
label = "Twitter"
url = "#"
[[params.footer.social.links]]
icon = "fa-facebook"
label = "Facebook"
url = "#"
[[params.footer.social.links]]
icon = "fa-instagram"
label = "Instagram"
url = "#"
[[params.footer.social.links]]
icon = "fa-github"
label = "Github"
url = "#"
[[params.footer.social.links]]
icon = "fa-dribbble"
label = "Dribbble"
url = "#"
[[params.footer.social.links]]
icon = "fa-linkedin"
label = "LinkedIn"
url = "#"
[[params.header.links]]
icon = "fa-info-circle"
name = "About"
url = "#footer"
