---
hide_body: false
is_partial: false
fields:
- name: albumthumb
  label: Albumthumb
  type: text
  hidden: false
  default: path/to/album/cover/image
pages:
- nature-photos/_index.md
- nature-photos/test-2.md
