---
label: default
hide_body: false
fields:
- name: albumthumb
  label: Albumthumb
  type: text
  hidden: false
  default: path/to/album/cover/image
pages:
- content/nature-photos/_index.md
- content/nature-photos/test-2.md
